---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-next-deployment-37348950
  labels:
    app: new-next-deployment-37348950
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: new-next-deployment-37348950
  template:
    metadata:
      labels:
        app: new-next-deployment-37348950
    spec:
      containers:
        - name: new-next-deployment-37348950
          image: docker.io/phengbunath/new-next-deployment-37348950:2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000